#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Already bootstrapped? The kit removes itself at the end of a successful run.
if [[ ! -d .scaffold ]]; then
  printf 'This project is already bootstrapped (.scaffold/ is gone). Nothing to do.\n'
  exit 0
fi

TOTAL_STAGES=7

# Custom opening frame — this wizard runs shell steps in place, not a browser
# journey, so it replaces the library's generic banner() copy.
_clear
printf '\n%s%s  Project bootstrap%s\n' "$BOLD" "$BLUE" "$RESET"
printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
say "This wizard bootstraps the project right here:"
step "verify the scaffold, then init git + the beads (bd) issue tracker"
step "install the agent skills as project-scoped Claude plugins"
step "record the bootstrap decision as an ADR bead"
step "hand the README rewrite to your coding agent"
step "finally the scaffold kit (.scaffold/ and this wizard) removes itself"
printf '\n'
note "Every step is idempotent — stop any time with Ctrl-C and re-run later."
pause "Ready to start?"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Preflight — tools and scaffold integrity"
say "Checking required tools: git, python3, bd (beads)."
missing=0
for tool in git python3 bd; do
  if command -v "$tool" >/dev/null 2>&1; then
    step "$tool — found"
  else
    warn "$tool — not installed"
    missing=1
  fi
done
if [[ "$missing" -ne 0 ]]; then
  warn "Install the missing tools and re-run this wizard."
  note "bd (beads): https://github.com/steveyegge/beads — e.g. 'brew install beads'"
  exit 1
fi
say "Verifying the scaffold against its manifest…"
bash .scaffold/verify.sh .

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Pick your coding agent"

# Agent roster — every CLI this wizard can drive, in default-preference order.
# Names are the binaries, except "cursor" (binary: agent, formerly cursor-agent).
# agent_status / run_agent below hold the per-CLI knowledge: how to tell whether
# it is logged in, and its verified headless + auto-approve invocation. Every
# headless run must auto-approve tool calls — without that, a CLI either hangs
# on a permission prompt (there is no TTY to answer it) or exits 0 having
# edited nothing. Flags were checked against these versions:
#   claude 2.1, codex 0.149, gemini 0.58, qwen 0.23, copilot 1.0, opencode 1.18,
#   pi 0.84, omp 18.0, kimi 1.50, goose 1.x, amp 2026-09, droid/crush/cursor/
#   kiro-cli/aider per their current docs.
AGENT_ROSTER="claude codex gemini qwen copilot opencode pi omp kimi goose amp droid crush cursor kiro-cli aider"

# agent_bin NAME — the executable behind a roster name.
agent_bin() {
  case "$1" in
    cursor) if command -v cursor-agent >/dev/null 2>&1 && ! command -v agent >/dev/null 2>&1; then
              echo cursor-agent; else echo agent; fi ;;
    *) echo "$1" ;;
  esac
}

# agent_status NAME — sets AGENT_STATE to warm (installed + logged in), cold
# (installed, definitely not logged in) or unknown (installed; no cheap probe),
# and AGENT_NOTE to a one-line hint. Probes must be quick and must never start
# a login flow themselves.
agent_status() {
  AGENT_STATE="unknown"; AGENT_NOTE="login state unknown"
  case "$1" in
    claude)
      if claude auth status >/dev/null 2>&1; then AGENT_STATE=warm; AGENT_NOTE="logged in"
      else AGENT_STATE=cold; AGENT_NOTE="not logged in (run 'claude' once to log in)"; fi ;;
    codex)
      if codex login status >/dev/null 2>&1; then AGENT_STATE=warm; AGENT_NOTE="logged in"
      else AGENT_STATE=cold; AGENT_NOTE="not logged in (run 'codex login')"; fi ;;
    gemini)
      if [[ -n "${GEMINI_API_KEY:-}" || -n "${GOOGLE_API_KEY:-}" || -f "$HOME/.gemini/oauth_creds.json" ]]; then
        AGENT_STATE=warm; AGENT_NOTE="API key or OAuth credentials found"
      else AGENT_NOTE="no GEMINI_API_KEY and no ~/.gemini/oauth_creds.json (run 'gemini' once to log in)"; fi ;;
    qwen)
      if [[ -f "$HOME/.qwen/oauth_creds.json" || -n "${OPENAI_API_KEY:-}" ]]; then
        AGENT_STATE=warm; AGENT_NOTE="credentials found"
      else AGENT_NOTE="no ~/.qwen/oauth_creds.json (run 'qwen' once to log in)"; fi ;;
    copilot)
      AGENT_NOTE="uses the Copilot login or COPILOT_GITHUB_TOKEN/GH_TOKEN (run 'copilot login' if it fails)" ;;
    opencode)
      local creds; creds="$(opencode auth list 2>/dev/null || true)"
      if [[ -z "$creds" ]]; then AGENT_NOTE="could not query 'opencode auth list'"
      elif printf '%s' "$creds" | grep -q ' 0 credentials'; then
        AGENT_STATE=cold; AGENT_NOTE="no stored credentials (run 'opencode auth login'; provider API keys in the env also work)"
      else AGENT_STATE=warm; AGENT_NOTE="credentials stored"; fi ;;
    pi|omp)
      # Print mode exits 0 with "No API key found" when no provider is logged
      # in — the only reliable probe is the model list (verified for pi; omp
      # is a pi fork and is assumed to behave the same).
      local models rc=0; models="$("$1" --list-models 2>&1)" || rc=$?
      if [[ "$rc" -ne 0 || -z "$models" ]]; then
        AGENT_NOTE="'$1 --list-models' failed: $(printf '%s' "$models" | head -n1 | cut -c1-60)"
      elif printf '%s' "$models" | grep -qi 'No models available'; then
        AGENT_STATE=cold; AGENT_NOTE="no provider logged in (run '$1' and /login)"
      else AGENT_STATE=warm; AGENT_NOTE="provider configured"; fi ;;
    kimi)
      if [[ -n "${KIMI_API_KEY:-}" ]] || [[ -d "$HOME/.kimi/credentials" && -n "$(ls -A "$HOME/.kimi/credentials" 2>/dev/null)" ]]; then
        AGENT_STATE=warm; AGENT_NOTE="credentials found"
      else AGENT_NOTE="no KIMI_API_KEY and no ~/.kimi/credentials (run 'kimi login')"; fi ;;
    goose)
      if [[ -f "$HOME/.config/goose/config.yaml" ]]; then AGENT_STATE=warm; AGENT_NOTE="provider configured"
      else AGENT_STATE=cold; AGENT_NOTE="no provider configured (run 'goose configure')"; fi ;;
    amp)
      AGENT_NOTE="opens a browser login if no API key is stored (AMP_API_KEY also works)" ;;
    droid)
      AGENT_NOTE="uses the droid login or FACTORY_API_KEY" ;;
    crush)
      AGENT_NOTE="uses provider API keys from its config or the env" ;;
    cursor)
      if "$(agent_bin cursor)" status >/dev/null 2>&1; then AGENT_STATE=warm; AGENT_NOTE="logged in"
      else AGENT_NOTE="'agent status' did not confirm a login (run 'agent login' or set CURSOR_API_KEY)"; fi ;;
    kiro-cli)
      if kiro-cli whoami >/dev/null 2>&1; then AGENT_STATE=warm; AGENT_NOTE="logged in"
      else AGENT_NOTE="'kiro-cli whoami' did not confirm a login (run 'kiro-cli login')"; fi ;;
    aider)
      AGENT_NOTE="uses provider API keys from the env (OPENAI_API_KEY, ANTHROPIC_API_KEY, …)" ;;
  esac
}

# run_agent NAME — invoke the CLI on $agent_prompt: headless, one shot, all
# tool calls auto-approved. stdin is /dev/null so nothing can wait on a TTY.
run_agent() {
  case "$1" in
    # edits only need acceptEdits; bypassPermissions would also allow shell
    claude)   claude -p --permission-mode acceptEdits "$agent_prompt" </dev/null ;;
    # --full-auto was removed from `codex exec`; this is the long form of --yolo
    # (a sandboxed alternative: `codex exec -s workspace-write`)
    codex)    codex exec --dangerously-bypass-approvals-and-sandbox "$agent_prompt" </dev/null ;;
    # --yolo is deprecated in favour of --approval-mode yolo
    gemini)   gemini --approval-mode yolo -p "$agent_prompt" </dev/null ;;
    # qwen: -p is deprecated; the positional prompt runs one-shot
    qwen)     qwen --yolo "$agent_prompt" </dev/null ;;
    # --allow-all-tools is required for -p (non-interactive) mode
    copilot)  copilot --allow-all-tools -p "$agent_prompt" </dev/null ;;
    # `opencode run` auto-denies permission prompts unless --auto is given
    opencode) opencode run --auto "$agent_prompt" </dev/null ;;
    # pi has no permission prompts at all
    pi)       pi -p "$agent_prompt" </dev/null ;;
    omp)      omp -p --yolo "$agent_prompt" </dev/null ;;
    # --print implies --afk (auto-approve); --yolo keeps older releases covered
    kimi)     kimi --print --yolo -p "$agent_prompt" </dev/null ;;
    goose)    GOOSE_MODE=auto goose run --no-session -t "$agent_prompt" </dev/null ;;
    # amp never asks for tool approval; -x is execute mode
    amp)      amp -x "$agent_prompt" </dev/null ;;
    # --auto high: highest autonomy short of --skip-permissions-unsafe
    droid)    droid exec --auto high "$agent_prompt" </dev/null ;;
    # `crush run` auto-approves every permission request (no flag needed)
    crush)    crush run "$agent_prompt" </dev/null ;;
    # --force (= --yolo): apply changes instead of only proposing them
    cursor)   "$(agent_bin cursor)" -p --force "$agent_prompt" </dev/null ;;
    kiro-cli) kiro-cli chat --no-interactive --trust-all-tools "$agent_prompt" </dev/null ;;
    aider)    aider --yes-always --no-auto-commits --message "$agent_prompt" </dev/null ;;
    *)        return 127 ;;
  esac
}

say "Looking for agent CLIs that are installed and logged in (warm)…"
default_cli=""; fallback_cli=""; installed_agents=""
for name in $AGENT_ROSTER; do
  command -v "$(agent_bin "$name")" >/dev/null 2>&1 || continue
  installed_agents="$installed_agents $name"
  agent_status "$name"
  case "$AGENT_STATE" in
    warm)    step "$name — installed, $AGENT_NOTE"
             [[ -z "$default_cli" ]] && default_cli="$name" ;;
    unknown) step "$name — installed ($AGENT_NOTE)"
             [[ -z "$fallback_cli" ]] && fallback_cli="$name" ;;
    cold)    warn "$name — installed but $AGENT_NOTE" ;;
  esac
done
[[ -z "$default_cli" ]] && default_cli="$fallback_cli"
if [[ -z "$default_cli" ]]; then
  if [[ -z "$installed_agents" ]]; then
    warn "No agent CLI found. Supported: $AGENT_ROSTER"
  else
    warn "No warm agent CLI found — log in to one of:$installed_agents"
  fi
  warn "The wizard will do the mechanical setup and leave the README rewrite"
  warn "for you (or an agent) to do later."
  default_cli="none"
fi
# select_agent — prompt until AGENT_CLI is an installed, driveable CLI or the
# explicit choice "none". Stage 6 re-invokes this after a failed agent run.
select_agent() {
  while :; do
    AGENT_CLI=""
    note "supported: $AGENT_ROSTER"
    ask AGENT_CLI "Agent to finish the setup (name, or none) [${default_cli}]:"
    [[ -z "$AGENT_CLI" ]] && AGENT_CLI="$default_cli"
    if [[ "$AGENT_CLI" == "none" ]]; then break; fi
    case " $AGENT_ROSTER " in
      *" $AGENT_CLI "*)
        if command -v "$(agent_bin "$AGENT_CLI")" >/dev/null 2>&1; then break; fi
        warn "'$AGENT_CLI' is not on PATH — install it, or pick another agent"
        ;;
      *)
        warn "'$AGENT_CLI' is not an agent this wizard can drive — choose one of"
        warn "the supported names above, or none"
        ;;
    esac
  done
  note "using: $AGENT_CLI"
}
select_agent

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Git and beads issue tracker"
if [[ ! -d .git ]]; then
  git init -b main >/dev/null
  step "git init -b main — done"
else
  note "git repository already present"
fi
bd init --init-if-missing --skip-agents --non-interactive </dev/null
step "bd init — done (--skip-agents keeps CLAUDE.md a single '@AGENTS.md' line)"
if bd setup codex --check >/dev/null 2>&1; then
  note "bd setup codex — already installed"
else
  bd setup codex </dev/null
  step "bd setup codex — beads guidance wired into AGENTS.md"
fi

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Agent skills (project-scoped Claude plugins)"
if command -v claude >/dev/null 2>&1; then
  say "Installing mattpocock-skills (official marketplace) and ponytail…"
  if claude plugin install mattpocock-skills --scope project </dev/null; then
    step "mattpocock-skills — installed"
  else
    claude plugin marketplace add mattpocock/skills --scope project </dev/null
    claude plugin install mattpocock-skills@mattpocock --scope project </dev/null
    step "mattpocock-skills — installed (via explicit marketplace)"
  fi
  claude plugin marketplace add DietrichGebert/ponytail --scope project </dev/null
  claude plugin install ponytail@ponytail --scope project </dev/null
  step "ponytail — installed"
  note "recorded in .claude/settings.json; available from the next agent session"
else
  SKIPPED+=("agent skills — claude CLI not installed; install it and run: claude plugin install mattpocock-skills --scope project")
  warn "claude CLI not found — skipping plugin installation"
fi

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Record the bootstrap decision (ADR bead)"
if bd list -t decision 2>/dev/null | grep -q "bootstrap: agent conventions adopted"; then
  note "bootstrap decision bead already recorded"
else
  bd create -t decision "bootstrap: agent conventions adopted" \
    -d "Conventions fixed at bootstrap: single instruction file (AGENTS.md; CLAUDE.md is only '@AGENTS.md'); issues and ADRs tracked in beads — ADRs are 'decision' beads, never docs/adr/; agent skills installed as project-scoped Claude plugins (mattpocock-skills, ponytail). Specs live in docs/agents/." \
    </dev/null
  step "decision bead created — ADRs live in beads (see docs/agents/domain.md)"
fi

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Let the agent finish — rewrite README.md"
agent_prompt="Read ./.scaffold/AGENT-SETUP.md and complete the agent tasks in it. You are non-interactive: never ask a question, use the documented defaults. End with the checklist report AGENT-SETUP.md asks for."

# readme_rewritten — the hard completion check from AGENT-SETUP.md: the
# onboarding README counts as rewritten once it no longer mentions this wizard.
readme_rewritten() {
  [[ -f README.md ]] && ! grep -q "setup-wizard.sh" README.md
}

# The agent's exit status alone is not trusted: a run only passes when the
# README check confirms the work. Anything else loops back to agent selection
# or is recorded loudly as not done — never skipped silently.
if readme_rewritten; then
  note "README.md already rewritten — nothing for the agent to do"
else
  agent_log="$(mktemp)"
  while :; do
    if [[ "$AGENT_CLI" == "none" ]]; then
      warn "No agent selected — README.md is still the scaffold onboarding page."
      if confirm "Really leave the README rewrite undone?"; then
        SKIPPED+=("README rewrite — NOT done; run an agent on ./.scaffold/AGENT-SETUP.md")
        warn "README rewrite NOT done — listed under 'still to do by hand'"
        break
      fi
      select_agent
      continue
    fi
    say "Running $AGENT_CLI — output streams below and is verified afterwards…"
    printf '  %s── %s ──%s\n' "$DIM" "$AGENT_CLI" "$RESET"
    rc=0
    run_agent "$AGENT_CLI" 2>&1 | tee "$agent_log" || rc=$?
    printf '  %s── end of %s output ──%s\n' "$DIM" "$AGENT_CLI" "$RESET"
    if [[ "$rc" -eq 0 ]] && readme_rewritten; then
      step "$AGENT_CLI finished — README.md no longer references the scaffold"
      say "Agent report (tail of its output):"
      tail -n 10 "$agent_log" | sed 's/^/    /'
      break
    fi
    if [[ "$rc" -ne 0 ]]; then
      warn "$AGENT_CLI exited with status $rc — the task did not complete"
    else
      warn "$AGENT_CLI exited 0, but README.md still mentions setup-wizard.sh —"
      warn "the rewrite did NOT happen"
    fi
    say "Last lines of the agent output:"
    tail -n 10 "$agent_log" | sed 's/^/    /'
    if confirm "Retry (pick the same or another agent)?"; then
      select_agent
      continue
    fi
    SKIPPED+=("README rewrite — FAILED with $AGENT_CLI; re-run the wizard or run an agent on ./.scaffold/AGENT-SETUP.md")
    warn "README rewrite NOT done — listed under 'still to do by hand'"
    break
  done
fi

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Remove the scaffold kit"
say "A bootstrapped project keeps no scaffold residue: .scaffold/ and this"
say "wizard both go away."
if ! readme_rewritten; then
  warn "README.md was NOT rewritten — removing .scaffold/ also deletes the"
  warn "agent instructions (.scaffold/AGENT-SETUP.md). Keep the kit until done."
fi
if confirm "Remove .scaffold/ and setup-wizard.sh now?"; then
  rm -rf .scaffold setup-wizard.sh
  step "scaffold kit removed"
else
  SKIPPED+=("scaffold kit removal — run: rm -rf .scaffold setup-wizard.sh")
fi
# ──────────────────────────────────────────────────────────────────────────

finish
printf '  %sNext%s: start your coding agent in this project and run\n' "$BOLD" "$RESET"
printf '  %s/mattpocock-skills:setup-matt-pocock-skills%s to finalize the skills\n' "$BLUE" "$RESET"
say "configuration. The answers are pre-baked in docs/agents/ (beads tracker,"
say "default triage labels, single-context + ADRs in beads) — accept the"
say "defaults, or adjust those files first."
printf '\n'
