#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Already bootstrapped? The kit removes itself at the end of a successful run.
if [[ ! -d .scaffold ]]; then
  printf 'This project is already bootstrapped (.scaffold/ is gone). Nothing to do.\n'
  exit 0
fi

TOTAL_STAGES=7

# Custom opening frame — this wizard runs shell steps in place, not a browser
# journey, so it replaces the library's generic banner() copy.
_clear
printf '\n%s%s  Project bootstrap%s\n' "$BOLD" "$BLUE" "$RESET"
printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
say "This wizard bootstraps the project right here:"
step "verify the scaffold, then init git + the beads (bd) issue tracker"
step "install the agent skills as project-scoped Claude plugins"
step "record the bootstrap decision as an ADR bead"
step "hand the README rewrite to your coding agent"
step "finally the scaffold kit (.scaffold/ and this wizard) removes itself"
printf '\n'
note "Every step is idempotent — stop any time with Ctrl-C and re-run later."
pause "Ready to start?"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Preflight — tools and scaffold integrity"
say "Checking required tools: git, python3, bd (beads)."
missing=0
for tool in git python3 bd; do
  if command -v "$tool" >/dev/null 2>&1; then
    step "$tool — found"
  else
    warn "$tool — not installed"
    missing=1
  fi
done
if [[ "$missing" -ne 0 ]]; then
  warn "Install the missing tools and re-run this wizard."
  note "bd (beads): https://github.com/steveyegge/beads — e.g. 'brew install beads'"
  exit 1
fi
say "Verifying the scaffold against its manifest…"
bash .scaffold/verify.sh .

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Pick your coding agent"
say "Looking for agent CLIs that are installed and logged in (warm)…"
default_cli=""
if command -v claude >/dev/null 2>&1; then
  if claude auth status >/dev/null 2>&1; then
    step "claude — installed, logged in"
    [[ -z "$default_cli" ]] && default_cli="claude"
  else
    warn "claude — installed but not logged in (run 'claude' once to log in)"
  fi
fi
if command -v codex >/dev/null 2>&1; then
  if codex login status >/dev/null 2>&1; then
    step "codex — installed, logged in"
    [[ -z "$default_cli" ]] && default_cli="codex"
  else
    warn "codex — installed but not logged in (run 'codex login')"
  fi
fi
if command -v kimi >/dev/null 2>&1; then
  step "kimi — installed (login state unknown)"
  [[ -z "$default_cli" ]] && default_cli="kimi"
fi
if [[ -z "$default_cli" ]]; then
  warn "No warm agent CLI found. The wizard will do the mechanical setup and"
  warn "leave the README rewrite for you (or an agent) to do later."
  default_cli="none"
fi
AGENT_CLI=""
ask AGENT_CLI "Agent to finish the setup [${default_cli}]:"
[[ -z "$AGENT_CLI" ]] && AGENT_CLI="$default_cli"
note "using: $AGENT_CLI"

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Git and beads issue tracker"
if [[ ! -d .git ]]; then
  git init -b main >/dev/null
  step "git init -b main — done"
else
  note "git repository already present"
fi
bd init --init-if-missing --skip-agents --non-interactive </dev/null
step "bd init — done (--skip-agents keeps CLAUDE.md a single '@AGENTS.md' line)"
if bd setup codex --check >/dev/null 2>&1; then
  note "bd setup codex — already installed"
else
  bd setup codex </dev/null
  step "bd setup codex — beads guidance wired into AGENTS.md"
fi

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Agent skills (project-scoped Claude plugins)"
if command -v claude >/dev/null 2>&1; then
  say "Installing mattpocock-skills (official marketplace) and ponytail…"
  if claude plugin install mattpocock-skills --scope project </dev/null; then
    step "mattpocock-skills — installed"
  else
    claude plugin marketplace add mattpocock/skills --scope project </dev/null
    claude plugin install mattpocock-skills@mattpocock --scope project </dev/null
    step "mattpocock-skills — installed (via explicit marketplace)"
  fi
  claude plugin marketplace add DietrichGebert/ponytail --scope project </dev/null
  claude plugin install ponytail@ponytail --scope project </dev/null
  step "ponytail — installed"
  note "recorded in .claude/settings.json; available from the next agent session"
else
  SKIPPED+=("agent skills — claude CLI not installed; install it and run: claude plugin install mattpocock-skills --scope project")
  warn "claude CLI not found — skipping plugin installation"
fi

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Record the bootstrap decision (ADR bead)"
if bd list -t decision 2>/dev/null | grep -q "bootstrap: agent conventions adopted"; then
  note "bootstrap decision bead already recorded"
else
  bd create -t decision "bootstrap: agent conventions adopted" \
    -d "Conventions fixed at bootstrap: single instruction file (AGENTS.md; CLAUDE.md is only '@AGENTS.md'); issues and ADRs tracked in beads — ADRs are 'decision' beads, never docs/adr/; agent skills installed as project-scoped Claude plugins (mattpocock-skills, ponytail). Specs live in docs/agents/." \
    </dev/null
  step "decision bead created — ADRs live in beads (see docs/agents/domain.md)"
fi

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Let the agent finish — rewrite README.md"
agent_prompt="Read ./.scaffold/AGENT-SETUP.md and complete the agent tasks in it. You are non-interactive: never ask a question, use the documented defaults."
case "$AGENT_CLI" in
  claude)
    say "Running claude (file edits only, so acceptEdits is enough)…"
    claude -p --permission-mode acceptEdits "$agent_prompt" </dev/null || {
      SKIPPED+=("README rewrite — claude run failed; re-run: claude -p --permission-mode acceptEdits \"$agent_prompt\"")
      warn "claude run failed — you can re-run it later"
    }
    ;;
  codex)
    say "Running codex…"
    codex exec --full-auto "$agent_prompt" </dev/null || {
      SKIPPED+=("README rewrite — codex run failed; re-run: codex exec --full-auto \"$agent_prompt\"")
      warn "codex run failed — you can re-run it later"
    }
    ;;
  kimi)
    SKIPPED+=("README rewrite — run kimi yourself with: \"$agent_prompt\"")
    warn "kimi invocation is not automated — run it with the prompt above"
    ;;
  *)
    SKIPPED+=("README rewrite — replace the onboarding README with your project's real README")
    note "skipping the agent step"
    ;;
esac

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Remove the scaffold kit"
say "A bootstrapped project keeps no scaffold residue: .scaffold/ and this"
say "wizard both go away."
if confirm "Remove .scaffold/ and setup-wizard.sh now?"; then
  rm -rf .scaffold setup-wizard.sh
  step "scaffold kit removed"
else
  SKIPPED+=("scaffold kit removal — run: rm -rf .scaffold setup-wizard.sh")
fi
# ──────────────────────────────────────────────────────────────────────────

finish
printf '  %sNext%s: start your coding agent in this project and run\n' "$BOLD" "$RESET"
printf '  %s/mattpocock-skills:setup-matt-pocock-skills%s to finalize the skills\n' "$BLUE" "$RESET"
say "configuration. The answers are pre-baked in docs/agents/ (beads tracker,"
say "default triage labels, single-context + ADRs in beads) — accept the"
say "defaults, or adjust those files first."
printf '\n'
